### ISSUE TITLE
ig-nav-drawer optimizations

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/igniteui-js-blocks#447]
### Description  
The ig-nav-drawer requires some optimization since it was developed on an earlier angular version.

**Comment by damyanpetev** [comment]
There seems to be a gestures issue with Hammer.js and Chrome 55+ (works in FF) due to changes to input events. As far as I cant tell pans (`touchmove`-like) get stuck past the initial trigger and swipes don't get recognized at all (due to pan stopping). Possibly related to https://github.com/hammerjs/hammer.js/issues/1065 and [others](https://github.com/hammerjs/hammer.js/issues/1084). Appears to be related to the target as changing the document handlers to body helped.

I see a similar issue with Carousel that uses `renderer.listen(this.elementRef.nativeElement, "swipeleft"..` and also fails on Chrome (though somehow a similar declarative handler works for the calendar just fine). I've logged #458 for that.

**Comment by damyanpetev** [comment]
Since this is a generic task, beyond the fix for gestures I do have some suggestions:
- Rename `<ig-nav-drawer>`  to `<igx-nav-drawer>` to align with other components
- Expose a `NavigationModule`[NNF] for the nav service and directives or include them in existing modules
- Use our pre-built animations - that might require our own app container component to work with pinned state, though.
- A mini-template version in the samples

@IG-Stanimir-Dimitrov , @kdinev thoughts/suggestions?

**Comment by IG-Stanimir-Dimitrov** [comment]
@damyanpetev , I agree on the first three points though some of the animations will be an overkill . What do you refer to by mini-template version?

**Comment by damyanpetev** [comment]
@IG-Stanimir-Dimitrov The drawer can have two templates, the mini is a visible collapsed state (e.g. just icons). Last points in the [spec stories](https://github.com/IgniteUI/igniteui-js-blocks/wiki/Navigation-Drawer-Specification#developer). The originals samples for component had one, and the new have the ideal icon setup to show that off as well.

**Comment by damyanpetev** [comment]
Actually an addition - since `pinThreshold` is evaluated on init only, it might be a good idea to add a resize handler to make it dynamic?

**Comment by IG-Stanimir-Dimitrov** [comment]
@damyanpetev , I agree - even a basic scenario like a rotating tablet will be handled much better if the `pinThreshold ` is evaluated reactively on resize.

**Comment by IG-Stanimir-Dimitrov** [comment]
This issue was closed with PR https://github.com/IgniteUI/igniteui-js-blocks/pull/465 

@damyanpetev , I will create a new issue for documenting the changes. Update specification as well.
