### ISSUE TITLE
Implement View loading in the tab component

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-js-blocks#68]
The tab should act like a navigation component in Android. It should support loading of different Views.

The syntax should be something of the sort:

```
<ig-tab-bar alignment="bottom"> 
  <ig-tab label="Home" href="#/Home" src="template_folder/template1.html" icon="home-icon-css-class"> 
  </ig-tab> 
  <ig-tab label="About" href="#/about" src="template_folder/template2.html" icon="about-icon-css-class"> 
  </ig-tab> 
</ig-tab-bar>
```

We can discuss the `src` attribute, it could be named something else, or we can create a view component that goes inside the tab and carries the src. This is just a brainstorm, so we can discuss this further.

**Comment by petko5kov** [comment]
It seems that Angular2 does not provide a way to load custom markup from source file on component level.
The loading should be happen on application level.

**Comment by samelliottdlt** [comment]
Hey guys. Saw this in my notifications so I thought I would chime in.

ReportPlus is migrating to Angular and one of the things I had to build was a dynamic dialog component such that a developer on our team can create a component, invoke a service and that component is rendered within the dialog. I think it is useful in your case; think tabs instead of dialogs.

It was heavily inspired by the resource available here: http://blog.rangle.io/dynamically-creating-components-with-angular-2/

Also, I think you can maybe use a ViewChild to get an elementRef and use jQuery to manaully insert into the DOM with some markup from some arbitrary source although I personally find this a lot less elegant.

The code I wrote is available in our internal TFS. We can discuss this if you guys feel this is something that makes sense to use.

**Comment by petko5kov** [comment]
The tabbar itself gives you a chance to put random content into its panels. But if you want to load a content from some other external file, then you need to implement your own solution. 
A demo how to achieve it is available in tabbar demo - the 3rd tab loads content from "template.html" file.
